import type { User, Business, Event, Church, PrayerGroup, Testimonial, VolunteerOpportunity, Message, SamaritanAlert } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'João Silva',
    avatar: 'https://i.pravatar.cc/150?img=1',
    profession: 'Engenheiro de Software',
    phone: '(62) 99999-0001',
    email: 'joao@email.com',
    isOnline: true,
    openToVisits: true,
    friends: ['u2', 'u3', 'u4'],
    location: { lat: -16.6864, lng: -49.2643, address: 'Setor Bueno, Goiânia' },
    homeLocation: { lat: -16.6864, lng: -49.2643, address: 'Setor Bueno, Goiânia' },
    churchId: 'c1',
    bio: 'Amante de tecnologia e da família.',
    helpOffer: 'Ajudo com problemas de computador, internet e pequenos reparos eletrônicos.',
  },
  {
    id: 'u2',
    name: 'Maria Santos',
    avatar: 'https://i.pravatar.cc/150?img=5',
    profession: 'Médica',
    phone: '(62) 99999-0002',
    email: 'maria@email.com',
    isOnline: true,
    openToVisits: false,
    friends: ['u1', 'u3'],
    location: { lat: -16.6780, lng: -49.2530, address: 'Jardim Goiás, Goiânia' },
    homeLocation: { lat: -16.6780, lng: -49.2530, address: 'Jardim Goiás, Goiânia' },
    churchId: 'c1',
    bio: 'Servindo a Deus através da medicina.',
    helpOffer: 'Posso orientar sobre saúde, primeiros socorros e encaminhar para atendimento médico.',
  },
  {
    id: 'u3',
    name: 'Pedro Oliveira',
    avatar: 'https://i.pravatar.cc/150?img=8',
    profession: 'Pastor',
    phone: '(62) 99999-0003',
    email: 'pedro@email.com',
    isOnline: false,
    openToVisits: true,
    friends: ['u1', 'u2', 'u4'],
    location: { lat: -16.6910, lng: -49.2710, address: 'Setor Oeste, Goiânia' },
    homeLocation: { lat: -16.6910, lng: -49.2710, address: 'Setor Oeste, Goiânia' },
    churchId: 'c1',
    bio: 'Servo do Senhor. Igreja Comunidade da Graça.',
    helpOffer: 'Estou disponível para orar, aconselhar e visitar idosos e enfermos.',
  },
  {
    id: 'u4',
    name: 'Ana Costa',
    avatar: 'https://i.pravatar.cc/150?img=9',
    profession: 'Professora',
    phone: '(62) 99999-0004',
    email: 'ana@email.com',
    isOnline: true,
    openToVisits: true,
    friends: ['u1', 'u3'],
    location: { lat: -16.6730, lng: -49.2580, address: 'Setor Marista, Goiânia' },
    homeLocation: { lat: -16.6730, lng: -49.2580, address: 'Setor Marista, Goiânia' },
    bio: 'Educadora apaixonada.',
    helpOffer: 'Dou aulas de reforço de português e matemática para crianças e adolescentes.',
  },
  {
    id: 'u5',
    name: 'Carlos Mendes',
    avatar: 'https://i.pravatar.cc/150?img=11',
    profession: 'Empresário',
    phone: '(62) 99999-0005',
    email: 'carlos@email.com',
    isOnline: false,
    openToVisits: false,
    friends: [],
    location: { lat: -16.6650, lng: -49.2450, address: 'Setor Aeroporto, Goiânia' },
    churchId: 'c2',
    helpOffer: 'Ajudo com transporte, mudanças e posso emprestar ferramentas de trabalho.',
  },
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: 'b1',
    name: 'Padaria do João',
    category: 'restaurante',
    location: { lat: -16.6850, lng: -49.2620, address: 'Rua T-28, Setor Bueno' },
    phone: '(62) 3333-0001',
    hours: 'Seg-Sáb: 6h às 20h | Dom: 7h às 13h',
    description: 'Padaria artesanal com pães frescos todo dia.',
    ownerId: 'u1',
    rating: 4.8,
    reviewCount: 127,
    loyaltyPoints: 100,
    communityRecommendations: ['u2', 'u3', 'u4'],
  },
  {
    id: 'b2',
    name: 'Clínica Saúde & Vida',
    category: 'saude',
    location: { lat: -16.6780, lng: -49.2500, address: 'Av. T-64, Jardim Goiás' },
    phone: '(62) 3333-0002',
    hours: 'Seg-Sex: 7h às 18h | Sáb: 7h às 12h',
    description: 'Clínica médica multidisciplinar com foco em atendimento humanizado.',
    ownerId: 'u2',
    rating: 4.9,
    reviewCount: 89,
    communityRecommendations: ['u1', 'u3'],
  },
  {
    id: 'b3',
    name: 'Mercado Comunitário',
    category: 'mercado',
    location: { lat: -16.6900, lng: -49.2680, address: 'Rua 18, Setor Oeste' },
    phone: '(62) 3333-0003',
    hours: 'Todos os dias: 7h às 22h',
    description: 'Produtos frescos e variedades para toda família.',
    ownerId: 'u3',
    rating: 4.5,
    reviewCount: 203,
    loyaltyPoints: 150,
    communityRecommendations: ['u1', 'u2', 'u4', 'u5'],
  },
  {
    id: 'b4',
    name: 'Escola Luz do Saber',
    category: 'educacao',
    location: { lat: -16.6720, lng: -49.2560, address: 'Av. C-9, Setor Marista' },
    phone: '(62) 3333-0004',
    hours: 'Seg-Sex: 7h às 18h',
    description: 'Escola cristã com excelência acadêmica e formação de valores.',
    ownerId: 'u4',
    rating: 4.7,
    reviewCount: 56,
    communityRecommendations: ['u1', 'u2'],
  },
];

export const MOCK_SAMARITAN_ALERTS: SamaritanAlert[] = [
  {
    id: 'sa1',
    userId: 'u4',
    userName: 'Ana Costa',
    userAvatar: 'https://i.pravatar.cc/150?img=9',
    type: 'practical_help',
    description: 'Pneu furado na Av. T-64! Preciso de ajuda para trocar ou conseguir um mecânico.',
    location: { lat: -16.6740, lng: -49.2570, address: 'Av. T-64, Setor Marista' },
    createdAt: new Date(Date.now() - 15 * 60 * 1000),
    status: 'active',
  },
  {
    id: 'sa2',
    userId: 'u2',
    userName: 'Maria Santos',
    userAvatar: 'https://i.pravatar.cc/150?img=5',
    type: 'prayer',
    description: 'Por favor, orem por minha mãe que está internada no hospital. Precisamos de fé e intercessão.',
    location: { lat: -16.6790, lng: -49.2540, address: 'Jardim Goiás, Goiânia' },
    createdAt: new Date(Date.now() - 45 * 60 * 1000),
    status: 'active',
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'Culto de Louvor e Adoração',
    description: 'Momento especial de adoração com toda a família de Deus. Venha adorar conosco!',
    type: 'religious',
    location: { lat: -16.6870, lng: -49.2640, address: 'Igreja Comunidade da Graça - Setor Bueno' },
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    organizer: 'Igreja Comunidade da Graça',
    organizerId: 'u3',
    attendees: ['u1', 'u2', 'u3'],
    churchId: 'c1',
  },
  {
    id: 'e2',
    title: 'Churrasco Comunitário',
    description: 'Encontro de amigos e famílias para um churrasco na área verde do Jardim Goiás.',
    type: 'social',
    location: { lat: -16.6760, lng: -49.2520, address: 'Parque Flamboyant, Jardim Goiás' },
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    organizer: 'João Silva',
    organizerId: 'u1',
    attendees: ['u1', 'u4'],
  },
  {
    id: 'e3',
    title: 'Arrecadação de Alimentos',
    description: 'Campanha de doação de alimentos para famílias carentes do Setor Leste.',
    type: 'volunteer',
    location: { lat: -16.6640, lng: -49.2430, address: 'Setor Aeroporto, Goiânia' },
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    organizer: 'Carlos Mendes',
    organizerId: 'u5',
    attendees: ['u2', 'u3', 'u5'],
  },
  {
    id: 'e4',
    title: 'Workshop: Empreendedorismo Cristão',
    description: 'Aprenda a gerir seu negócio com princípios bíblicos e éticos.',
    type: 'business',
    location: { lat: -16.6860, lng: -49.2620, address: 'Escola Luz do Saber' },
    date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    organizer: 'Ana Costa',
    organizerId: 'u4',
    attendees: ['u1', 'u5'],
  },
];

export const MOCK_CHURCHES: Church[] = [
  {
    id: 'c1',
    name: 'Igreja Comunidade da Graça',
    denomination: 'Evangélica',
    location: { lat: -16.6870, lng: -49.2640, address: 'Rua T-28, Setor Bueno, Goiânia' },
    phone: '(62) 3232-0001',
    schedule: 'Dom: 9h e 19h | Qua: 19h30 | Sex: 20h',
    pastor: 'Pedro Oliveira',
    description: 'Uma comunidade de fé que busca viver o amor de Cristo no dia a dia.',
    members: 450,
  },
  {
    id: 'c2',
    name: 'Paróquia São José',
    denomination: 'Católica',
    location: { lat: -16.6650, lng: -49.2440, address: 'Rua 23, Setor Aeroporto, Goiânia' },
    phone: '(62) 3232-0002',
    schedule: 'Sáb: 18h | Dom: 7h, 9h, 11h, 18h',
    pastor: 'Pe. Antônio',
    description: 'Paróquia que serve a comunidade há mais de 60 anos com amor e dedicação.',
    members: 1200,
  },
  {
    id: 'c3',
    name: 'Congregação Batista Central',
    denomination: 'Batista',
    location: { lat: -16.6720, lng: -49.2560, address: 'Av. C-9, Setor Marista, Goiânia' },
    phone: '(62) 3232-0003',
    schedule: 'Dom: 9h e 18h | Qua: 19h30',
    pastor: 'Pr. Roberto',
    description: 'Congregação batista comprometida com o ensino da Palavra e missões.',
    members: 320,
  },
];

export const MOCK_PRAYER_GROUPS: PrayerGroup[] = [
  {
    id: 'pg1',
    name: 'Guerreiros da Oração',
    description: 'Grupo de intercessão que se reúne semanalmente para orar pelos enfermos e necessitados.',
    churchId: 'c1',
    isOnline: false,
    schedule: 'Terças-feiras às 19h',
    members: ['u1', 'u2', 'u3'],
    creatorId: 'u3',
    topic: 'Intercessão',
  },
  {
    id: 'pg2',
    name: 'Estudo Bíblico Online',
    description: 'Grupo de estudo da Bíblia pelo WhatsApp e reunião online semanal.',
    isOnline: true,
    schedule: 'Quintas-feiras às 20h (online)',
    members: ['u1', 'u4'],
    creatorId: 'u1',
    topic: 'Estudo Bíblico',
  },
  {
    id: 'pg3',
    name: 'Jovens em Missão',
    description: 'Grupo de jovens engajados em missões locais e evangelismo.',
    churchId: 'c2',
    isOnline: false,
    schedule: 'Sábados às 15h',
    members: ['u4', 'u5'],
    creatorId: 'u5',
    topic: 'Missões',
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    userId: 'u2',
    title: 'Cura milagrosa',
    content: 'Fui diagnosticada com uma doença grave e, depois de muita oração e fé, o Senhor me curou completamente. Os médicos ficaram surpresos com minha recuperação. Glória a Deus!',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    likes: ['u1', 'u3'],
    comments: [
      { id: 'tc1', userId: 'u1', content: 'Que testemunho lindo! Deus é fiel!', createdAt: new Date() },
    ],
  },
  {
    id: 't2',
    userId: 'u1',
    title: 'Restauração familiar',
    content: 'Nossa família estava em crise, pensávamos que o casamento acabaria. Com aconselhamento na igreja e muita oração, Deus restaurou nosso lar. Hoje somos mais unidos do que nunca!',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    likes: ['u2', 'u3', 'u4'],
    comments: [],
  },
  {
    id: 't3',
    userId: 'u3',
    title: 'Provisão sobrenatural',
    content: 'Estava sem emprego há 3 meses, com dívidas e sem saber o que fazer. Confiei no Senhor e, em uma semana, recebi 3 propostas de emprego. Deus provê!',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    likes: ['u1', 'u2'],
    comments: [],
  },
];

export const MOCK_VOLUNTEER: VolunteerOpportunity[] = [
  {
    id: 'v1',
    title: 'Distribuição de Marmitas',
    description: 'Ajude a distribuir marmitas para pessoas em situação de rua no Centro de Goiânia.',
    organizerId: 'u3',
    organizerName: 'Igreja Comunidade da Graça',
    location: { lat: -16.6899, lng: -49.2648, address: 'Centro de Goiânia' },
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    spots: 20,
    enrolled: ['u1', 'u2'],
    category: 'Assistência Social',
  },
  {
    id: 'v2',
    title: 'Aulas de Reforço Escolar',
    description: 'Voluntários para dar aulas de reforço de matemática e português para crianças carentes.',
    organizerId: 'u4',
    organizerName: 'Escola Luz do Saber',
    location: { lat: -16.6720, lng: -49.2560, address: 'Setor Marista, Goiânia' },
    date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    spots: 10,
    enrolled: ['u4'],
    category: 'Educação',
  },
  {
    id: 'v3',
    title: 'Mutirão de Limpeza',
    description: 'Vamos limpar e revitalizar o parque do bairro. Traga luvas e vontade de ajudar!',
    organizerId: 'u5',
    organizerName: 'Carlos Mendes',
    location: { lat: -16.6760, lng: -49.2520, address: 'Parque Flamboyant' },
    date: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
    spots: 50,
    enrolled: ['u1', 'u3', 'u5'],
    category: 'Meio Ambiente',
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'm1',
    fromUserId: 'u2',
    toUserId: 'u1',
    content: 'Oi João! Vai vir no culto amanhã?',
    createdAt: new Date(Date.now() - 60 * 60 * 1000),
    read: true,
  },
  {
    id: 'm2',
    fromUserId: 'u1',
    toUserId: 'u2',
    content: 'Com certeza! Já falei com a Ana também.',
    createdAt: new Date(Date.now() - 45 * 60 * 1000),
    read: true,
  },
  {
    id: 'm3',
    fromUserId: 'u2',
    toUserId: 'u1',
    content: 'Ótimo! Passarei em casa antes.',
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
    read: false,
  },
  {
    id: 'm4',
    fromUserId: 'u3',
    toUserId: 'u1',
    content: 'João, o estudo bíblico de quinta confirma?',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: false,
  },
];
